ACCESS_TOKEN_LIFE: 86400000
API_KEY: VanThuan.HoangAnh.dmFudGh1YW5ob2FuZ2FuaDIwMjM=
REFRESH_TOKEN_LIFE: 8.64E7
server:
  servlet:
    context-path: /digital.library
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 1669871043
    url: jdbc:mysql://localhost:3306/digital_library
    username: root
  devtools:
    restart:
      log-condition-evaluation-delta: false
  jackson:
    time-zone: Asia/Bangkok
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        globally_quoted_identifiers: true
      show_sql: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
springdoc:
  api-docs:
    path: /api/v1/api-docs
  swagger-ui:
    operationsSorter: method
    path: /api/v1/swagger-ui
    try-it-out-enabled: true